name: Terraform checks
on: [push, pull_request]

jobs:
  terraform-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init-zpa-service-edge-group
        run: |
          cd modules/terraform-zpa-service-edge-group
          terraform init

      - name: Terraform Validate
        id: validate-zpa-service-edge-group
        run: |
          cd modules/terraform-zpa-service-edge-group
          terraform validate -no-color

      - name: Terraform Init
        id: init-zpa-provisioning-key
        run: |
          cd modules/terraform-zpa-provisioning-key
          terraform init

      - name: Terraform Validate
        id: validate-zpa-provisioning-key
        run: |
          cd modules/terraform-zpa-provisioning-key
          terraform validate -no-color

      - name: Terraform Init
        id: init-zpse-vm-azure
        run: |
          cd modules/terraform-zpse-vm-azure
          terraform init

      - name: Terraform Validate
        id: validate-zpse-vm-azure
        run: |
          cd modules/terraform-zpse-vm-azure
          terraform validate -no-color

      - name: Terraform Init
        id: init-zpse-bastion-azure
        run: |
          cd modules/terraform-zpse-bastion-azure
          terraform init

      - name: Terraform Validate
        id: validate-zpse-bastion-azure
        run: |
          cd modules/terraform-zpse-bastion-azure
          terraform validate -no-color

      - name: Terraform Init
        id: init-zpse-network-azure
        run: |
          cd modules/terraform-zpse-network-azure
          terraform init

      - name: Terraform Validate
        id: validate-zpse-network-azure
        run: |
          cd modules/terraform-zpse-network-azure
          terraform validate -no-color

      - name: Terraform Init
        id: init-zpse-nsg-azure
        run: |
          cd modules/terraform-zpse-nsg-azure
          terraform init

      - name: Terraform Validate
        id: validate-zpse-nsg-azure
        run: |
          cd modules/terraform-zpse-nsg-azure
          terraform validate -no-color
